# Generated by Django 6.0.7 on 2026-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copyright',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
