# Generated by Django 6.0.7 on 2026-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_image',
            field=models.ImageField(blank=True, upload_to='photos/pages'),
        ),
    ]
